name: Auto-Sync Configs

on:
  schedule:
    - cron: '*/30 * * * *'  # every 30 minutes
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Rename Configs
      run: |
        sed -i 's/FREE2CONFIG/shahabprv/g' *.txt

    - name: Commit and Push Changes
      run: |
        git config --global user.name "shahabprv"
        git config --global user.email "shahabprv@example.com"
        git add .
        git diff --cached --quiet || git commit -m "Auto sync with renamed configs"
        git push origin main
